### Monitors
#
# Monitor 1:
output HDMI-A-1 resolution 1920x1080@60Hz position 0,0
# Monitor 2:
output DP-1 resolution 1920x1080@120Hz position 1920,0

### Input Devices
#
## Keyboard
input type:keyboard {
    xkb_layout "us"
    xkb_numlock enabled
    }
#
## Mouse
input type:pointer {
    accel_profile "flat"    # acceleration
    pointer_accel -0.25       # speed
    }
#
#
## Tablet 
input 9580:110:HUION_420 {
    map_to_output HDMI-A-1
    map_from_region 0.35x0.35 0.75x0.75
  }
