default_border pixel 2
default_floating_border pixel 2

focus_follows_mouse yes

gaps inner 1
gaps outer 1

client.focused #A0ACFE #A0ACFE #A0ACFE #A0ACFE
client.unfocused #292C3D #292C3D #292C3D #292C3D


