exec waybar  # status bar
exec mako           # notifications
exec nm-applet &    # networkManager applet

exec /usr/lib/mate-polkit/polkit-mate-authentication-agent-1
exec dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=sway
exec kbuildsycoca6
