mouse_warping none
#set the variables
set {
	$game inhibit_idle focus; floating enable; fullscreen enable; shadows disable
	$popup floating enable; sticky enable; shadows enable
	$float floating enable;
	$video inhibit_idle fullscreen; max_render_time off
	$important inhibit_idle open; floating enable
  $termfloat floating enable; resize set 900 600; move position center
}
for_window {
#popup - floating enable; sticky enable
  [app_id="xdg-desktop-portal-gtk"] $popup
	[app_id="firefox" title="^Picture-in-Picture$"] $popup
	[app_id="galculator"] $popup
	[title="(?:Open|Save) (?:File|Folder|As)" app_id="caja|file-roller"] $popup
	[title="^(File|Folder)\s*Already Exists\s*—\s*" app_id="caja|file-roller"] $popup
	[title="Confirm to replace files" app_id="caja|file-roller"] $popup
	[app_id="pavucontrol"] $popup

#float - floating enable; border pixel 1
	[title="^Information\s*—\s*Dolphin" app_id="dolphin"] $float
	[title="^Loading archive" app_id="org.kde.ark"] $float
  [app_id="anki"] $float
	[window_role="pop-up,task_dialog,About"] $float;
	[window_type="dialog"] $float;
	[window_type="utility"] $float;
	[window_type="toolbar"] $float;
	[window_type="splash"] $float;
	[window_type="menu"] $float;
	[window_type="dropdown_menu"] $float;
	[window_type="popup_menu"] $float;
	[window_type="tooltip"] $float;
	[window_type="notification"] $float;

#video - inhibit_idle fullscreen; border none; max_render_time off
	[instance="chromium"] $video
	[app_id="mpv"] $video
	[class="firefox"] $video
	[app_id="firefox"] $video

#important - inhibit_idle open; floating enable; border pixel 1
	[title="Move files" app_id="dolphin|org.kde.ark|pcmanfm|pcmanfm-qt"] $important
	[title="^(Copying|Moving)\s*—\s*Dolphin" app_id="dolphin|org.kde.ark|pcmanfm|pcmanfm-qt"] $important
	[title="^Extracting\s" app_id="(dolphin|org.kde.ark)"] $important
	[title="Copy Files" app_id="dolphin|org.kde.ark|pcmanfm|pcmanfm-qt"] $important
	[title="Delete Files" app_id="dolphin|org.kde.ark|pcmanfm|pcmanfm-qt"] $important
	[title="Compressing (.*) — Ark" app_id="org.kde.ark"] $important; resize set width 18 ppt


#termfloat
  [app_id="termfloat"] $termfloat
}

